### ISSUE TITLE
Helm chart should support broker ingress configuration/disable override

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/service-fabrik-broker#1347]
**Is your feature request related to a problem? Please describe.**
Id like to use interoperator with complete control of exposition

**Describe the solution you'd like**
Additionnal config in values.yml to disable ingress, and or add custom annotation/description for exposition

**Describe alternatives you've considered**
Create a Service out of the helm chart, using same selector to target the pods

**Additional context**

**Comment by anoopjb** [comment]
Unfortunately we cannot tackle this soon. Also we are open for contributions.

**Comment by anoopjb** [comment]
Hi, @poblin-orange,
An option for passing annotations to ingress is handled in  #1717. I hope this helps.

**Comment by pivotal-marcela-campo** [comment]
Closing as per previous comment and no other activity since then
